
import os
LINE_CHANNEL_TOKEN = os.getenv("LINE_CHANNEL_TOKEN", "")
LINE_USER_ID = os.getenv("LINE_USER_ID", "")
GOLD_SYMBOL = "OANDA:XAUUSD"
TIMEFRAME = "5m"
CANDLE_COUNT = 53
PATTERN_SIMILARITY_THRESHOLD = 55
CHECK_INTERVAL_MINUTES = 5
